name: Zenodo Update

on:
  push:
    branches: [ main ]
    paths:
      #- '**.txt'
      #- '**.md'
      - '**.csv'
      #- '.github/pictures/**'
  workflow_dispatch:
env:
  zenodo_deposition_id: 6644127
  zenodo_server: 'https://zenodo.org'
jobs:
  new_version:
    name: Create new version of zenodo deposition
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
         lfs: 'true'

      - uses: kykrueger/zenodo-new-version@v1.0.2
        with:
         whitelist_replace_doi: .github/workflows/.zenodo_whitelist_replace_doi
         zenodo_deposition_id: ${{ env.zenodo_deposition_id }}
         zenodo_server: ${{ env.zenodo_server }}
         zenodo_token: ${{ secrets.ZENODO_TOKEN }}

      # Build Documentation pdf's
      - name: CreateWorkingDir
        run: mkdir md2pdf & cp Readme*.md md2pdf/ 
        
      # Build pdfs  
      - uses: baileyjm02/markdown-to-pdf@v1.2.0
        with:
          input_dir: md2pdf/
          output_dir: md2pdf/
          image_import: /.github/pictures   #Uncomment if u use imgges in your Readme.md
          images_dir: /.github/pictures     #Uncomment if u use imgges in your Readme.md
          build_html: false
      
      # Renames Readme.pdf to 'Dokumentation <reponame>.pdf'
      - name: Rename Readme.pdf
        run: mv md2pdf/Readme.pdf "[Dokumentation]_$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' ).pdf"
      - name: Rename Readme_en.pdf
        run: |
          if [ -f md2pdf/Readme_en.pdf ]; then
             mv md2pdf/Readme_en.pdf "[Documentation]_$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' ).pdf"
          fi  
      
      - name: DeleteWorkingDir
        run: rm -rf md2pdf 

      - uses: kykrueger/zenodo-publish@v1.0.3
        with:
          zenodo_metadata: Metadaten/zenodo.json
          whitelist_uploads: .github/workflows/.zenodo_whitelist_uploads
          zenodo_deposition_id: ${{ env.zenodo_deposition_id }}
          zenodo_server: ${{ env.zenodo_server }}
          zenodo_token: ${{ secrets.ZENODO_TOKEN }}
      - uses: EndBug/add-and-commit@v7.1.1
        with:
          message: 'published to Zenodo'
